### ISSUE TITLE
Bug Report: Duplicate Matricule Error in "Create New Technician" Page

### ISSUE THREAD

**Issue by REp007** [Eren-yeager13/TopTech#1]
#### Description:
When attempting to create a new technician, if a duplicate matricule is entered (one that already exists for another technician), an error is thrown by Laravel. This issue needs to be handled more gracefully to improve the user experience.

#### Steps to Reproduce:
1. Navigate to the "Create New Technician" page.
2. Enter a matricule that already exists in the system.
3. Attempt to submit the form.

#### Expected Behavior:
A user-friendly error message should be displayed, indicating that the matricule is already in use, and the user should be prompted to enter a unique matricule.

#### Actual Behavior:
An unhandled Laravel error is displayed, which is not user-friendly.

#### Suggested Solution:
Implement exception handling to catch the duplicate matricule error. Display a clear and concise error message to the user, prompting them to enter a unique matricule. This can be achieved by:
- Validating the matricule before submission.
- Catching the exception thrown by Laravel and handling it gracefully.

#### Additional Context:
Providing a more user-friendly error message will improve the overall user experience and prevent confusion when entering data.

**Comment by Eren-yeager13** [comment]
thank you for your time in reviews and testing, this bug has been solved for any other bugs please feel free to tell me about
